id: P006667
initial_creation_type: ocr
source_metadata:
  id: bdr:W8871
  title: དྲི་བ་རྣམ་པར་རྒྱལ་བའི་དྲིས་ལན་ལུང་རིག་འབྱུང་གནས
  author: ''
  volumes:
    19e667915afb4c3ebc8063e82f239e31:
      image_group_id: I1931
      title: ''
      volume_number: 1
      total_pages: 53
      base_file: v001.txt
