id: P006667
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:14:41.573071
source_metadata:
  id: bdr:W8871
  title: དྲི་བ་རྣམ་པར་རྒྱལ་བའི་དྲིས་ལན་ལུང་རིག་འབྱུང་གནས
  author: ''
  volumes:
    19e667915afb4c3ebc8063e82f239e31:
      image_group_id: I1931
      title: ''
      volume_number: 1
      total_pages: 53
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
